from typing import List, Optional, Protocol, runtime_checkable

from .models import SearchPage, SearchResult, Tweet, TweetPage, User, UserPage, UserProfile

@runtime_checkable
class Provider(Protocol):
    async def search(self, query: str, category: str = "Latest", limit: int = 20) -> SearchPage: ...
    async def user_by_username(self, username: str) -> Optional[UserProfile]: ...
    async def user_by_id(self, user_id: str) -> Optional[UserProfile]: ...
    async def user_timeline(self, username: str, limit: int = 20) -> TweetPage: ...
    async def user_tweets(self, username: str, limit: int = 20) -> TweetPage: ...
    async def user_following(self, username: str, limit: int = 100) -> UserPage: ...
    async def user_followers(self, username: str, limit: int = 100) -> UserPage: ...
    async def user_likes(self, username: str, limit: int = 20) -> TweetPage: ...
    async def user_media(self, username: str, limit: int = 20) -> TweetPage: ...
    async def user_tweets_and_replies(self, username: str, limit: int = 20) -> TweetPage: ...
    async def tweet_detail(self, tweet_id: str) -> Optional[Tweet]: ...
    async def tweet_retweeters(self, tweet_id: str, limit: int = 100) -> UserPage: ...
    async def tweet_favoriters(self, tweet_id: str, limit: int = 100) -> UserPage: ...

    # Backward compatibility
    async def user_info(self, username: str) -> Optional[User]: ...
    async def close(self) -> None: ...

class SearchProvider(Protocol):
    async def search(self, query: str, category: str = "Latest", limit: int = 20) -> SearchPage: ...

class UserProvider(Protocol):
    async def user_info(self, username: str) -> Optional[User]: ...
    async def user_tweets(self, username: str, limit: int = 20) -> List[Tweet]: ...

class TweetProvider(Protocol):
    async def tweet_details(self, tweet_id: str) -> Optional[Tweet]: ...

class ProviderFactory(Protocol):
    def create(self) -> Provider: ...
