#!/bin/bash
set -e

# This script helps with the initial setup of the local development environment.

# --- Help ---
if [[ "$1" == "--help" ]]; then
    echo "Usage: ./scripts/bootstrap_local.sh"
    echo ""
    echo "This script performs the following actions:"
    echo "1. Checks for the existence of '.env'."
    echo "2. If '.env' does not exist, it generates a new one with secure, random credentials for local PostgreSQL development."
    echo "3. If '.env' already exists, it does nothing to avoid overwriting your configuration."
    exit 0
fi

# --- Main ---
echo "Bootstrapping local environment..."

# Check if .env already exists
if [ -f ".env" ]; then
    echo ".env file already exists. Skipping creation."
    exit 0
fi

# Check for openssl
if ! command -v openssl &> /dev/null
then
    echo "Error: openssl command not found. It is required to generate random passwords."
    echo "Please install openssl and try again."
    exit 1
fi

echo "Creating a new .env file for local development..."

# Generate random user and password
# Using hex for url-safe characters
PG_USER="dev_user_$(openssl rand -base64 6 | tr -d '+/=' | tr '[:upper:]' '[:lower:]')"
PG_PASSWORD=$(openssl rand -hex 24)
PG_DB="xservice"

# Create the .env file
cat << EOF > .env
# This file was generated by scripts/bootstrap_local.sh for local development.
# DO NOT COMMIT THIS FILE.

# --- Database Configuration ---
# Configured for local PostgreSQL instance via Docker Compose.
DATABASE_URL=postgresql://${PG_USER}:${PG_PASSWORD}@localhost:5432/${PG_DB}

# If you want to use a local SQLite database instead, comment out the line above
# and uncomment the one below.
# DATABASE_URL=sqlite:///./xservice-dev.db

# --- Docker Compose PostgreSQL Initialization ---
# These credentials are required by the postgres container on its first run.
POSTGRES_USER=${PG_USER}
POSTGRES_PASSWORD=${PG_PASSWORD}
POSTGRES_DB=${PG_DB}
EOF

echo ".env file created with secure, random credentials for local PostgreSQL."
echo "You can now run 'docker compose up' to start the development environment."
echo "Bootstrap complete."